title: Robert L. Blum Ph.D.
email: robert.blum@yale.edu
logo: /IMG_2105.JPG
description: # this means to ignore newlines until "baseurl:"
  Robby Blum's personal/professional website
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  robbyblum

theme: jekyll-theme-minimal
